# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-6.12.62-guix.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''linux-libre-6.12.62-guix.tar.zst-builder''; path = ./../sources/y9k0krwqwm2jyjrgb2rpc09rmix7qw5k-linux-libre-6.12.62-guix.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "linux-libre-6.12.62-guix.tar.zst-builder"; path = ./../sources/y9k0krwqwm2jyjrgb2rpc09rmix7qw5k-linux-libre-6.12.62-guix.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/hdq2f10s5kgdas5jzziqbz5xs6k544cd-linux-libre-arm-export-__sync_icache_dcache.patch.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/4i75vxknj6n2rz885nrq1xpjnj9ns6vi-linux-libre-6.12.62-guix.tar.xz.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/fc0szin7l1w71dr57rz6mr80895krq3r-100gnu+freedo.patch.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
