# Generated by guix-transfer
builtins.derivation {
  name = "coreutils-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''coreutils-runtime-env-builder''; path = ./../sources/256rzlpx0ygj30b602hgr97mq62i7vv4-coreutils-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "coreutils-runtime-env-builder"; path = ./../sources/256rzlpx0ygj30b602hgr97mq62i7vv4-coreutils-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/plwy702aas07vcngxb16270q1hiaj028-gmp-6.3.0.nix).out} ${(import ../store/4g3yk42gcmjg44xgri8hf29qm3yxl8lz-acl-2.3.1.nix).out} ${(import ../store/0nribzj5rwbcawganswg39wq83pqial9-libcap-2.64.nix).out} ${(import ../store/1r7ml8wichijf5wf0d0j8yksp7sagsfz-coreutils-9.1.nix).out} ${(import ../store/5zy2lhwi10xg8x3dq3jkkp12b0yy43da-attr-2.5.1.nix).out}";
}
