# Generated by guix-transfer
builtins.derivation {
  name = "autoconf-wrapper-2.69";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''autoconf-wrapper-2.69-builder''; path = ./../sources/6hd8ym2x9bc6wq0mp3yiwzscxl0yzjay-autoconf-wrapper-2.69-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "autoconf-wrapper-2.69-builder"; path = ./../sources/6hd8ym2x9bc6wq0mp3yiwzscxl0yzjay-autoconf-wrapper-2.69-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/p0njwyfxfrkhxnfy9p6k2dzfp5wax0qy-m4-1.4.19.nix).out} ${(import ../store/kpb781zr9m8qbfxks1826ridkcw5j9w5-perl-5.36.0.nix).out} ${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/al585zfr2ydg7jn7dzzy2mjhndfmy7v2-bash-minimal-5.2.37.nix).out} ${(import ../store/45w080s6clwyw7ncn6cskh4nys7dfkv9-autoconf-2.69.tar.xz.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out} ${(import ../store/4ar87qbsqh6yjzjwb8awvyx8p9p83s5w-autoconf-2.69.nix).out}";
}
