# Generated by guix-transfer
builtins.derivation {
  name = "shepherd-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''shepherd-runtime-env-builder''; path = ./../sources/grz630yxjippcmw5qk0ypcq3lqm8mvfw-shepherd-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "shepherd-runtime-env-builder"; path = ./../sources/grz630yxjippcmw5qk0ypcq3lqm8mvfw-shepherd-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/w5b1np7ri8m7ci675bbn7dhgay75ghcr-zstd-1.5.6.nix).out} ${(import ../store/lpwa7vsr9bssdazyfp01lrfbpfvnpn4x-shepherd-1.0.9.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out} ${(import ../store/jrgxs2yb827hw0pcw34wvlw157zy5r0k-guile-fibers-1.4.2.nix).out}";
}
