# Generated by guix-transfer
builtins.derivation {
  name = "patch-2.8.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+Hzuae7CtPy/YKOWsDCtaqNBXxkqpffuhMrV4R9/WuM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/patch-2.8.tar.xz/sha256/1qssgwgy3mfahkpgg99a35gl38vamlqb15m3c2zzrd62xrlywz7q";
}
