# Generated by guix-transfer
builtins.derivation {
  name = "zstd-1.5.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-6zPlH0mhXgI5UM14Jcp0pKK0Pbg1SCWsJPwbfuCeb6M=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/zstd-1.5.7.tar.gz/sha256/18vgkvh7w6zw4jn2aj1mp0yv98m4fk52ay6da0wh4pm194gyaczb";
}
