# Generated by guix-transfer
builtins.derivation {
  name = "texlive-amsfonts-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/i97lsjrdjrls7l0flyny57aihsxj3xk2-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-K6hjUPYrhXimPhtncgX/IL0cUMpPnTHvAaaoqzr7EF4=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "43,168,99,80,246,43,133,120,166,62,27,103,114,5,255,32,189,28,80,202,79,157,49,239,1,166,168,171,58,251,16,94";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/fonts/amsfonts/\" \"fonts/afm/public/amsfonts/cm/\" \"fonts/afm/public/amsfonts/cmextra/\" \"fonts/afm/public/amsfonts/cyrillic/\" \"fonts/afm/public/amsfonts/euler/\" \"fonts/afm/public/amsfonts/latxfont/\" \"fonts/afm/public/amsfonts/symbols/\" \"fonts/map/dvips/amsfonts/\" \"fonts/source/public/amsfonts/cmextra/\" \"fonts/source/public/amsfonts/cyrillic/\" \"fonts/source/public/amsfonts/dummy/\" \"fonts/source/public/amsfonts/symbols/\" \"fonts/tfm/public/amsfonts/cmextra/\" \"fonts/tfm/public/amsfonts/cyrillic/\" \"fonts/tfm/public/amsfonts/dummy/\" \"fonts/tfm/public/amsfonts/euler/\" \"fonts/tfm/public/amsfonts/symbols/\" \"fonts/type1/public/amsfonts/cm/\" \"fonts/type1/public/amsfonts/cmextra/\" \"fonts/type1/public/amsfonts/cyrillic/\" \"fonts/type1/public/amsfonts/euler/\" \"fonts/type1/public/amsfonts/latxfont/\" \"fonts/type1/public/amsfonts/symbols/\" \"source/latex/amsfonts/\" \"tex/latex/amsfonts/\" \"tex/plain/amsfonts/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).debug} ${(import ../store/qk9zgwdm7jg88a7fmw6nlp6zgdykazbw-subversion-1.14.5.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out}";
}
