# Generated by guix-transfer
builtins.derivation {
  name = "sudo-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''sudo-runtime-env-builder''; path = ./../sources/b7kiwi0wi6nwnbx6pk9dfhzmkh76dkwl-sudo-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "sudo-runtime-env-builder"; path = ./../sources/b7kiwi0wi6nwnbx6pk9dfhzmkh76dkwl-sudo-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/1r7ml8wichijf5wf0d0j8yksp7sagsfz-coreutils-9.1.nix).out} ${(import ../store/3ywnviw7qj7r4aq7d3sbb1jsxxnarsa7-linux-pam-1.5.2.nix).out} ${(import ../store/0jn8hc70m424i8qbkbd5i1wc5cky0cyl-sudo-1.9.17p1.nix).out} ${(import ../store/hsfkwglj2qzj7mlibrr34ga0rwspf53p-zlib-1.3.1.nix).out}";
}
