# Generated by guix-transfer
builtins.derivation {
  name = "readline-8.2.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''readline-8.2.tar.zst-builder''; path = ./../sources/055kamhs8chv27d8fkwnvyhfkgarryzv-readline-8.2.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "readline-8.2.tar.zst-builder"; path = ./../sources/055kamhs8chv27d8fkwnvyhfkgarryzv-readline-8.2.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "readline-link-ncurses.patch"; path = ./../sources/32bwvphbvn7p230knqfs2566sdbi9ik9-readline-link-ncurses.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 14))";
  __phantom_deps = "${(import ../store/0j5n5yfrwxlq7fvpvm2xd26c054hpylv-readline82-004.nix).out} ${(import ../store/pyip7wy6zbjn97b8ixsknfyar1a9viiz-readline-8.2.tar.gz.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/jcbip7wlwllcprkzyrw56vjdcv499gyr-readline82-006.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/am9nxgivlv4qn6jz5fcz6kyfjcdc5v6f-readline82-010.nix).out} ${(import ../store/l38alsmaaxd0kbhcip0fqkmzgvhf93vs-readline82-011.nix).out} ${(import ../store/68cka07i2y97kz1bkv9yhcwgvlnn53qi-readline82-007.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/1zzcsi82yls4wj6r015k30f6psx4ap1b-readline82-013.nix).out} ${(import ../store/vz26d25lcmc3amjwigmqz7cms4v46gna-readline82-012.nix).out} ${(import ../store/qh9ki9hcyqf4nwr7fd7ixapgc6yqxhxv-readline82-005.nix).out} ${(import ../store/wh5kn9k5f4k3qx05lxpibpp7m77rmhxs-readline82-001.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/3iiv5j44xk9qq5c4kr4l6dj7dm8ds3kn-readline82-008.nix).out} ${(import ../store/axc52dq8v6njprzd593jjf0pcwaz3l8j-readline82-009.nix).out} ${(import ../store/m4h9ja7611j7yfl9gxwcd7hy12yvqb60-readline82-003.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/r3mzf6z7mnsmm76vv9zz8f0m1aa71lxg-readline82-002.nix).out}";
}
