# Generated by guix-transfer
builtins.derivation {
  name = "suitesparse-5.13.0-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''suitesparse-5.13.0-checkout-builder''; path = ./../sources/j8sk8zy12a6m6n012fvb8wm8l9a2mz5m-suitesparse-5.13.0-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "suitesparse-5.13.0-checkout-builder"; path = ./../sources/j8sk8zy12a6m6n012fvb8wm8l9a2mz5m-suitesparse-5.13.0-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "suitesparse-mongoose-cmake.patch"; path = ./../sources/i7z7q33i75mxbz6pd2725mq4lzs40kf0-suitesparse-mongoose-cmake.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/iabi0vw6ffwki2yk5kj7nk0cxvz2ysvp-suitesparse-5.13.0-checkout.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
