# Generated by guix-transfer
builtins.derivation {
  name = "e2fsprogs-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''e2fsprogs-runtime-env-builder''; path = ./../sources/1xb6a09qnvzaw6325bmhdn58ggyflw8k-e2fsprogs-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "e2fsprogs-runtime-env-builder"; path = ./../sources/1xb6a09qnvzaw6325bmhdn58ggyflw8k-e2fsprogs-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/jy3x6qsmfvhymrxf4hpzx0fvyxmqpfhl-util-linux-2.40.4.nix).lib} ${(import ../store/bw6afp4xwys5id6mw20drln9r36yk1jv-e2fsprogs-1.47.2.nix).out}";
}
