# Generated by guix-transfer
builtins.derivation {
  name = "bash-mesboot-5.2.37";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''bash-mesboot-5.2.37-builder''; path = ./../sources/lfxb4js8vb468crhwwdq6v48c19szrwn-bash-mesboot-5.2.37-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "bash-mesboot-5.2.37-builder"; path = ./../sources/lfxb4js8vb468crhwwdq6v48c19szrwn-bash-mesboot-5.2.37-builder; })
  ];
  outputs = ["doc" "out"];
  LC_CTYPE = "C.UTF-8";
  allowedReferences = "out";
  __phantom_deps = "${(import ../store/pk4gwnc3fl5yyv3067wnvdaghd6r0nn9-gcc-mesboot-4.9.4.nix).out} ${(import ../store/sjm0lzfypcbx3m38w3wx5n5fily3xw1i-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/vplz8hy2cq1371cvvnnbhpn5q5mq602r-bash-5.2.tar.xz.nix).out} ${(import ../store/3qlr64nvpxqabkwy8xh38vnhmb8bsxp0-glibc-mesboot-2.16.0.nix).out} ${(import ../store/f3jv0abf796dvc16wjyzgh4ga4715j9r-gawk-mesboot-3.1.8.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/g6y4w2snrgl1ccip9bkcv1p9by9zld94-gcc-mesboot-wrapper-4.9.4.nix).out} ${(import ../store/riq6mqzhvnxpwx3wk1dfy7npl8kqz89l-make-mesboot-3.82.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out} ${(import ../store/h91qgk3x4wcwlw20vfvws3c92fgqs274-binutils-mesboot-2.20.1a.nix).out}";
}
