# Generated by guix-transfer
builtins.derivation {
  name = "binutils-2.44.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-2.44.tar.xz-builder''; path = ./../sources/f53djy7zbmz9pkhm3yn6rzbv65g7bmnc-binutils-2.44.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "binutils-loongson-workaround.patch"; path = ./../sources/zhx3zch54xs01i4pi5675xfkd4fix9b7-binutils-loongson-workaround.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "binutils-2.41-fix-cross.patch"; path = ./../sources/4432hk9wr0a70vgnxsj8jlfp9k6mnmig-binutils-2.41-fix-cross.patch; })
    (builtins.path { name = "binutils-2.44.tar.xz-builder"; path = ./../sources/f53djy7zbmz9pkhm3yn6rzbv65g7bmnc-binutils-2.44.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out} ${(import ../store/3ay2f76mz77n73xsxcq716326sxyvx5x-binutils-2.44.tar.bz2.nix).out}";
}
