# Generated by guix-transfer
builtins.derivation {
  name = "Python-3.11.14.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''Python-3.11.14.tar.zst-builder''; path = ./../sources/5xlqdg6q8vj99mqnxkhijzkyzhfhggan-Python-3.11.14.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "python-3-deterministic-build-info.patch"; path = ./../sources/46q4lgbhbqg6bspswcc437bfw0smb9pi-python-3-deterministic-build-info.patch; })
    (builtins.path { name = "python-3-hurd-configure.patch"; path = ./../sources/pdwyhwcr0iyirfgqcmrgj7xvxf3vnvz5-python-3-hurd-configure.patch; })
    (builtins.path { name = "python-3-search-paths.patch"; path = ./../sources/npn8j9gip9c7xk8zh8p53l6sjjpz6454-python-3-search-paths.patch; })
    (builtins.path { name = "python-3.11-fix-tests.patch"; path = ./../sources/v1b3wrk61lbz0qh64j4az1382q7hyfz9-python-3.11-fix-tests.patch; })
    (builtins.path { name = "Python-3.11.14.tar.zst-builder"; path = ./../sources/5xlqdg6q8vj99mqnxkhijzkyzhfhggan-Python-3.11.14.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 4))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/jz6biw8x8bwvgs3gf40475li18cp75bk-Python-3.11.14.tar.xz.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
