# Generated by guix-transfer
builtins.derivation {
  name = "python-ruamel.yaml.clib-0.2.12-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import''; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/jgv80dmpxr83xz62nj3gngp2yvwva78z-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''python-ruamel.yaml.clib-0.2.12-checkout-builder''; path = ./../sources/v47kil4mda2f1if9rv9ysd6lyy1p1bdg-python-ruamel.yaml.clib-0.2.12-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import"; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; })
    (builtins.path { name = "python-ruamel.yaml.clib-0.2.12-checkout-builder"; path = ./../sources/v47kil4mda2f1if9rv9ysd6lyy1p1bdg-python-ruamel.yaml.clib-0.2.12-checkout-builder; })
  ];
  outputHash = "sha256-VKiNt2WJttVjMR0z4bvdSYKOZqycRONCSPQacAy5PYo=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "84,168,141,183,101,137,182,213,99,49,29,51,225,187,221,73,130,142,102,172,156,68,227,66,72,244,26,112,12,185,61,138";
  "hg ref changeset" = "0.2.12";
  "hg ref url" = "http://hg.code.sf.net/p/ruamel-yaml-clib/code";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).debug} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/rdkcm6s41s1gzc52nilxqsafmg1nmbh9-mercurial-7.1.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out}";
}
