# Generated by guix-transfer
builtins.derivation {
  name = "tbb-2021.6.0-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''tbb-2021.6.0-checkout-builder''; path = ./../sources/g0zz6q90b2mw04gxvd68mbszlqn8bpmq-tbb-2021.6.0-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "tbb-2021.6.0-checkout-builder"; path = ./../sources/g0zz6q90b2mw04gxvd68mbszlqn8bpmq-tbb-2021.6.0-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "tbb-gcc-14.patch"; path = ./../sources/vnxgaixv65bkj1a0v9vvsncl1qg47y0l-tbb-gcc-14.patch; })
    (builtins.path { name = "tbb-other-arches.patch"; path = ./../sources/q6z6n7vnix60z49hkhhf1kwkh9w4v2jg-tbb-other-arches.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/5wg7ymdizf0fi7k7rzl0m06a0wicz628-tbb-2021.6.0-checkout.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
