# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-6.12.62-guix.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''linux-libre-6.12.62-guix.tar.xz-builder''; path = ./../sources/v3xviwnqbza3q8w77vxwdmf4f5l4g5lv-linux-libre-6.12.62-guix.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "linux-libre-6.12.62-guix.tar.xz-builder"; path = ./../sources/v3xviwnqbza3q8w77vxwdmf4f5l4g5lv-linux-libre-6.12.62-guix.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/f292g58bzw3zcrxdwm24r3rz4qvlcbg9-linux-libre-deblob-6.12.62-gnu.nix).out} ${(import ../store/sd75dr2iv6aa6aicf84km8r6cqw0a523-bash-5.2.37.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/0wwg2ganpbif26wqz4kfllf323s2zf90-gawk-5.3.0.nix).out} ${(import ../store/dirlwhp9lcr2a7m7ry9q29jv24c26g29-linux-6.12.62.tar.xz.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/z323vlxml09c6jy6kisjp9ixk4fknq0a-patch-2.8.nix).out} ${(import ../store/pqkx49kj6b9v9sfc79pbisrylc0rwq8g-coreutils-9.1.nix).out} ${(import ../store/40s7gkf7jganh51vvs9lxh4sgvhls7hb-python-wrapper-3.11.14.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/yypwx3p2rzfffld50b55z1c1qsjma4fx-diffutils-3.12.nix).out} ${(import ../store/bvl4ill7rbq0rnic5fld07ra5k69simc-grep-3.11.nix).out} ${(import ../store/hb1p3098wgrblsz08jzyn1g81a35lx44-sed-4.9.nix).out} ${(import ../store/6gyj6s1l2ivmck253mx51sbm1iscgz75-linux-libre-deblob-check-6.12.62-gnu.nix).out} ${(import ../store/rp8yv6yxmdvqzx5hcl4g4jbzhga4k6iv-findutils-4.10.0.nix).out}";
}
