# Generated by guix-transfer
builtins.derivation {
  name = "mes-boot-0.25.1";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''mes-boot-0.25.1-builder''; path = ./../sources/0r75rdk641q1p3adrqnaz9ib3pif76bl-mes-boot-0.25.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "mes-boot-0.25.1-builder"; path = ./../sources/0r75rdk641q1p3adrqnaz9ib3pif76bl-mes-boot-0.25.1-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/jkn8f43grmssjkm55dc7irx8aws0a4wx-mes-0.25.1.tar.gz.nix).out} ${(import ../store/dyrdkd4752xbrr1xrvnar682l09kvms4-stage0-posix-1.6.0.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/sm8zw9z09x5dqnbwnlpkq4hf99r543j9-nyacc-1.00.2.tar.gz.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out}";
}
