# Generated by guix-transfer
builtins.derivation {
  name = "llvm-project-19.1.7-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''llvm-project-19.1.7-checkout-builder''; path = ./../sources/dhsw32ad96lj44m9rjah9ms1z4ib6b40-llvm-project-19.1.7-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "clang-18.0-libc-search-path.patch"; path = ./../sources/pcb1i08i91z134isznqf8s5sik0l1yrp-clang-18.0-libc-search-path.patch; })
    (builtins.path { name = "llvm-project-19.1.7-checkout-builder"; path = ./../sources/dhsw32ad96lj44m9rjah9ms1z4ib6b40-llvm-project-19.1.7-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "clang-17.0-link-dsymutil-latomic.patch"; path = ./../sources/q5zyligsbr6bywanfjbsgszy1zfpzk32-clang-17.0-link-dsymutil-latomic.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/a48l8d63m5n1mjxxd3qn57gqcmaf7pqk-llvm-project-19.1.7-checkout.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
