# Generated by guix-transfer
builtins.derivation {
  name = "net-base-5.3";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''net-base-5.3-builder''; path = ./../sources/k8ld3ywg6pqfbmrshclki3i4k29cpc14-net-base-5.3-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "net-base-5.3-builder"; path = ./../sources/k8ld3ywg6pqfbmrshclki3i4k29cpc14-net-base-5.3-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/xszrqvdmg6hybxf84hsg9q0kcl8hagag-netbase_5.3.tar.xz.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out} ${(import ../store/23iksirmjjs0mb8nxrg7mfdqdc05w9ak-xz-5.4.5.nix).out}";
}
