# Generated by guix-transfer
builtins.derivation {
  name = "gnome-backgrounds-46.0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''j6fmbrwhvwsbk0wka86xpxafs48v6nqj-module-import''; path = ./../sources/kywphgpapd6yjxzkq666fga35qgqds3g-j6fmbrwhvwsbk0wka86xpxafs48v6nqj-module-import; }}"
    "-C"
    "${(import ../store/f8al19bshns4i8wdnjqxqyjrh5bnnzyz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gnome-backgrounds-46.0-builder''; path = ./../sources/bh5fsyn30m3b51wl6irzmhj3n3irf3ma-gnome-backgrounds-46.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gnome-backgrounds-46.0-builder"; path = ./../sources/bh5fsyn30m3b51wl6irzmhj3n3irf3ma-gnome-backgrounds-46.0-builder; })
    (builtins.path { name = "j6fmbrwhvwsbk0wka86xpxafs48v6nqj-module-import"; path = ./../sources/kywphgpapd6yjxzkq666fga35qgqds3g-j6fmbrwhvwsbk0wka86xpxafs48v6nqj-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/gba0pl3qwvzwwprccdrwqmn2mk90dv4f-gcc-14.3.0.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).out} ${(import ../store/p3433p8apcjvic6599dgwhjhjl021h1s-file-5.46.nix).out} ${(import ../store/nyhdyxrcxl2cfyinfi2d02fiw0vwm9b1-gnome-backgrounds-46.0.tar.xz.nix).out} ${(import ../store/xhc955ds83dwm39hffzy9iz7nhzhqirb-bash-minimal-5.2.37.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/0wwg2ganpbif26wqz4kfllf323s2zf90-gawk-5.3.0.nix).out} ${(import ../store/rp9hiq87ggb5gj04s2xv9rqrj7r37z3k-ld-wrapper-0.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/r2yswzwr1rkzk5bd6mnn3ac1cj63nk49-meson-1.9.0.nix).out} ${(import ../store/g4b580d737bvwaj9asqmfaqr750qgl14-gettext-minimal-0.23.1.nix).out} ${(import ../store/v0bqkz3ga4yxiiwws5sada1wz0mzbndf-linux-libre-headers-6.12.17.nix).out} ${(import ../store/pqkx49kj6b9v9sfc79pbisrylc0rwq8g-coreutils-9.1.nix).out} ${(import ../store/nnr9i1y08pmanflzdp3wrg3harv57y2h-ninja-1.13.2.nix).out} ${(import ../store/7lczvd4rfk1nahv0af9zknkxm6jj3js9-binutils-2.44.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/fjb6sh02qcv17h2zqifb2hwaf3klhrky-make-4.4.1.nix).out} ${(import ../store/yypwx3p2rzfffld50b55z1c1qsjma4fx-diffutils-3.12.nix).out} ${(import ../store/bvl4ill7rbq0rnic5fld07ra5k69simc-grep-3.11.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/hb1p3098wgrblsz08jzyn1g81a35lx44-sed-4.9.nix).out} ${(import ../store/rp8yv6yxmdvqzx5hcl4g4jbzhga4k6iv-findutils-4.10.0.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).static}";
}
