# Generated by guix-transfer
builtins.derivation {
  name = "icu4c-73_1-src.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''icu4c-73_1-src.tar.zst-builder''; path = ./../sources/i983281mdrz6z2an0ipbxa5dv05kic6m-icu4c-73_1-src.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "icu4c-fix-TestHebrewCalendarInTemporalLeapYear.patch"; path = ./../sources/d6bif7vnndkmmsw8qd2f9gk5bjaghx89-icu4c-fix-TestHebrewCalendarInTemporalLeapYear.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "icu4c-73_1-src.tar.zst-builder"; path = ./../sources/i983281mdrz6z2an0ipbxa5dv05kic6m-icu4c-73_1-src.tar.zst-builder; })
    (builtins.path { name = "icu4c-icu-22132-fix-vtimezone.patch"; path = ./../sources/4pvffws6j7c9jjqr0c7n5d5qkkfdr02y-icu4c-icu-22132-fix-vtimezone.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/37vn3kr9bns5sy5xfj5qjf9bwqgx654q-icu4c-73_1-src.tgz.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
