# Generated by guix-transfer
builtins.derivation {
  name = "iputils-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''iputils-runtime-env-builder''; path = ./../sources/684lqk9zmz96ij57hswxryirdkg28xys-iputils-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "iputils-runtime-env-builder"; path = ./../sources/684lqk9zmz96ij57hswxryirdkg28xys-iputils-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/0nribzj5rwbcawganswg39wq83pqial9-libcap-2.64.nix).out} ${(import ../store/i6bvdjf8zzc7vwpd1hyx9v17rrsyzvzr-iputils-20250605.nix).out} ${(import ../store/na7qqfh8f7xc0jhwmxcp56gz8wa3anna-libidn2-2.3.7.nix).out} ${(import ../store/r111fh4qh4kasjyb5wj1n1k7pzip17mz-openssl-3.0.8.nix).out}";
}
