# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/iputils/iputils"; rev = "refs/tags/20250605"; hash = "sha256-AJgNPIE90kALu4ihANELr9Dh28LhJ4camLksOIRV8Xo="; name = "iputils-20250605-checkout"; fetchSubmodules = false; }
