# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-deblob-check-6.12.62-gnu";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-EgmZM1+zdcOfV7vnLJZ/IJaHNT9hI2lCIIU8k8YhhPo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/linux-libre-deblob-check-6.12.62-gnu/sha256/1yl447396g454116j8v17wsqg5i0gyb2rrxvaygw6xdkbwrrj28j";
}
