# Generated by guix-transfer
builtins.derivation {
  name = "dhcpcd-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''dhcpcd-runtime-env-builder''; path = ./../sources/sgfac93ypr5b2xv6f1ih3lj8q6xpl4i4-dhcpcd-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "dhcpcd-runtime-env-builder"; path = ./../sources/sgfac93ypr5b2xv6f1ih3lj8q6xpl4i4-dhcpcd-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/kybabx9cg42f977ncl3ndm1c153hqa0q-eudev-3.2.14.nix).out} ${(import ../store/m4d2dvmry7qq6giibrc87pifm902rk88-coreutils-minimal-9.1.nix).out} ${(import ../store/00a72g3md15hx1d0cs2wi2ax0g6jsmyn-sed-4.9.nix).out} ${(import ../store/al585zfr2ydg7jn7dzzy2mjhndfmy7v2-bash-minimal-5.2.37.nix).out} ${(import ../store/ap8ykc0i017fldirw72kkxwcc3ic9lc5-dhcpcd-10.3.0.nix).out}";
}
