# Generated by guix-transfer
builtins.derivation {
  name = "python-setuptools-67.6.1";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import''; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/a9zs8ch8ya7c5lma4wndxgbp48spka69-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''python-setuptools-67.6.1-builder''; path = ./../sources/cglidic78f5dxbvzw6kczag9zmb4qgzk-python-setuptools-67.6.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "python-setuptools-67.6.1-builder"; path = ./../sources/cglidic78f5dxbvzw6kczag9zmb4qgzk-python-setuptools-67.6.1-builder; })
    (builtins.path { name = "sanity-check.py"; path = ./../sources/09lx08cjsa3ppv6aindzi8dh3y3nqs8r-sanity-check.py; })
    (builtins.path { name = "qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import"; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/gba0pl3qwvzwwprccdrwqmn2mk90dv4f-gcc-14.3.0.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).out} ${(import ../store/p3433p8apcjvic6599dgwhjhjl021h1s-file-5.46.nix).out} ${(import ../store/xhc955ds83dwm39hffzy9iz7nhzhqirb-bash-minimal-5.2.37.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/5k81ncj8g0kkiqmn0j9h3fdrg6xy3h8d-setuptools-67.6.1.tar.zst.nix).out} ${(import ../store/0wwg2ganpbif26wqz4kfllf323s2zf90-gawk-5.3.0.nix).out} ${(import ../store/rp9hiq87ggb5gj04s2xv9rqrj7r37z3k-ld-wrapper-0.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/v0bqkz3ga4yxiiwws5sada1wz0mzbndf-linux-libre-headers-6.12.17.nix).out} ${(import ../store/pqkx49kj6b9v9sfc79pbisrylc0rwq8g-coreutils-9.1.nix).out} ${(import ../store/rd13b7j89v585jw7a3zafnh38x9jg6j4-python-wrapper-3.11.14.nix).out} ${(import ../store/frzkn0lc0h6q1wg5iz5sv7vfpalza77h-python-wheel-0.40.0.nix).out} ${(import ../store/7lczvd4rfk1nahv0af9zknkxm6jj3js9-binutils-2.44.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/fjb6sh02qcv17h2zqifb2hwaf3klhrky-make-4.4.1.nix).out} ${(import ../store/yypwx3p2rzfffld50b55z1c1qsjma4fx-diffutils-3.12.nix).out} ${(import ../store/bvl4ill7rbq0rnic5fld07ra5k69simc-grep-3.11.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/41jsrkn9744bjm92qzzfv2kkxr5s07im-python-3.11.14.nix).out} ${(import ../store/hb1p3098wgrblsz08jzyn1g81a35lx44-sed-4.9.nix).out} ${(import ../store/rp8yv6yxmdvqzx5hcl4g4jbzhga4k6iv-findutils-4.10.0.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).static}";
}
