# Generated by guix-transfer
builtins.derivation {
  name = "bc-1.08.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-rkcP7EKXdWU+BCAV7cko0HyMOy/Fl2UXKjMNPYd4X4Y=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bc-1.08.2.tar.gz/sha256/11jzg23ks39k58bnb5y55wxqqz6h534ys5900hz6axcp8bn0yixf";
}
