# Generated by guix-transfer
builtins.derivation {
  name = "guile-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-runtime-env-builder''; path = ./../sources/llssrlspa5wc4fplkla6amvq6l6g2953-guile-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "guile-runtime-env-builder"; path = ./../sources/llssrlspa5wc4fplkla6amvq6l6g2953-guile-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/rj00swz82v153kjvhna9pqrgnazykp2a-libffi-3.4.6.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/x8wnhf1f9dq7daq30dasl09m26mj4cm1-libxcrypt-4.4.38.nix).out} ${(import ../store/al585zfr2ydg7jn7dzzy2mjhndfmy7v2-bash-minimal-5.2.37.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out}";
}
