# Generated by guix-transfer
builtins.derivation {
  name = "guile-fibers-1.3.1-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-fibers-1.3.1-checkout-builder''; path = ./../sources/sgr9xwgvnf7gjiy30a5fh95ijglsxyqw-guile-fibers-1.3.1-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "guile-fibers-1.3.1-checkout-builder"; path = ./../sources/sgr9xwgvnf7gjiy30a5fh95ijglsxyqw-guile-fibers-1.3.1-checkout-builder; })
    (builtins.path { name = "guile-fibers-libevent-timeout.patch"; path = ./../sources/si8ca90qdxvgn85gqhh71bhk62gczgpb-guile-fibers-libevent-timeout.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "guile-fibers-libevent-32-bit.patch"; path = ./../sources/cpnpvlmsjbac2n77shqjmdv24mdjxhrx-guile-fibers-libevent-32-bit.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/6sp0b27rl3sz8zfxqz872ycmzc6r7a6x-guile-fibers-1.3.1-checkout.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
