# Generated by guix-transfer
builtins.derivation {
  name = "xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-EyTrn3QCZlMlXTpE2jEDMY47jgf1dxFdf6WuE2LrM0U=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  url = "https://ftpmirror.gnu.org/guix/bootstrap/i686-linux/xz?id=44f07d1dc6806e97c4e9ee3e6be883cc59dc666e";
  executable = "1";
}
