# Generated by guix-transfer
builtins.derivation {
  name = "nss-certs-for-test-3.101.4";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import''; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; }}"
    "-C"
    "${(import ../store/97kflrq1silykxwcfzabjri4y48li1kp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''nss-certs-for-test-3.101.4-builder''; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "nss-certs-for-test-3.101.4-builder"; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; })
    (builtins.path { name = "m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import"; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/i0zld7h5hvfgxlbnhvjgziybhlffdk85-nss-certs-3.101.4.nix).out}";
}
