# Generated by guix-transfer
builtins.derivation {
  name = "glibc-headers-mesboot-2.16.0";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''glibc-headers-mesboot-2.16.0-builder''; path = ./../sources/3dz3pzrdv9ndyr9m8pwshyyb0ly89zy1-glibc-headers-mesboot-2.16.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "glibc-headers-mesboot-2.16.0-builder"; path = ./../sources/3dz3pzrdv9ndyr9m8pwshyyb0ly89zy1-glibc-headers-mesboot-2.16.0-builder; })
    (builtins.path { name = "glibc-bootstrap-system-2.2.5.patch"; path = ./../sources/9mnwbqwj5srxz907nlbr2kdm4j40hh41-glibc-bootstrap-system-2.2.5.patch; })
    (builtins.path { name = "glibc-boot-2.2.5.patch"; path = ./../sources/gs6hpx68k146ayvrc4cjka5713gbklay-glibc-boot-2.2.5.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/sjm0lzfypcbx3m38w3wx5n5fily3xw1i-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/f3jv0abf796dvc16wjyzgh4ga4715j9r-gawk-mesboot-3.1.8.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/bjv98x503w425i4r4bssyz8s6q8pfbp8-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/riq6mqzhvnxpwx3wk1dfy7npl8kqz89l-make-mesboot-3.82.nix).out} ${(import ../store/znzjy8p744ccrwb95fahjcwpj3in9ffn-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out} ${(import ../store/70wwhn07k24w1xwvz6ya6k2b5pn2dxsj-mesboot-headers-0.25.1.nix).out} ${(import ../store/b8jba9q1bdijcsj0qxmjaijkpjpi93yi-glibc-2.16.0.tar.xz.nix).out} ${(import ../store/h91qgk3x4wcwlw20vfvws3c92fgqs274-binutils-mesboot-2.20.1a.nix).out}";
}
