# Generated by guix-transfer
builtins.derivation {
  name = "tiff-4.4.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''tiff-4.4.0.tar.zst-builder''; path = ./../sources/4yb5faaw1pb3px9jsc2k9bj2k00vcgsq-tiff-4.4.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libtiff-CVE-2022-34526.patch"; path = ./../sources/8ay47k3sgg990qinqi12a7aa4qqr40kq-libtiff-CVE-2022-34526.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "tiff-4.4.0.tar.zst-builder"; path = ./../sources/4yb5faaw1pb3px9jsc2k9bj2k00vcgsq-tiff-4.4.0.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/lsdsvqk1dvd8m13a8h8vsxxrx8kq9vf3-tiff-4.4.0.tar.xz.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
