# Generated by guix-transfer
builtins.derivation {
  name = "texlive-metafont-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/i97lsjrdjrls7l0flyny57aihsxj3xk2-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-enliZEtUXi2yFap/1G7vb4QD7dbr8rxe6xOyv8NsjRM=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "122,121,98,100,75,84,94,45,178,21,170,127,212,110,239,111,132,3,237,214,235,242,188,94,235,19,178,191,195,108,141,19";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/man/man1/inimf.1\" \"doc/man/man1/inimf.man1.pdf\" \"doc/man/man1/mf-nowin.1\" \"doc/man/man1/mf-nowin.man1.pdf\" \"doc/man/man1/mf.1\" \"doc/man/man1/mf.man1.pdf\" \"metafont/base/\" \"metafont/config/\" \"metafont/misc/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).debug} ${(import ../store/qk9zgwdm7jg88a7fmw6nlp6zgdykazbw-subversion-1.14.5.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out}";
}
