# Generated by guix-transfer
builtins.derivation {
  name = "bootstrap-binaries-0";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''bootstrap-binaries-0-builder''; path = ./../sources/3aw732x69lihm41dpw1zvh5ap6h8srfm-bootstrap-binaries-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "bootstrap-binaries-0-builder"; path = ./../sources/3aw732x69lihm41dpw1zvh5ap6h8srfm-bootstrap-binaries-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/vaqbvb45b8asl4ahw4wjj9nn3vrrpdf1-tar.nix).out} ${(import ../store/gjyad63a6i1hmg01rasl9n3i28qdfhl2-static-binaries.tar.xz.nix).out} ${(import ../store/8yfxma06bb92ivhkc4mqg3ichbsljxkv-xz.nix).out}";
}
