# Generated by guix-transfer
builtins.derivation {
  name = "docbook-xml-4.2.zip";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''docbook-xml-4.2.zip-builder''; path = ./../sources/c76q39xsl9myhy2a7id1wlqvl4zrlzmi-docbook-xml-4.2.zip-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "docbook-xml-4.2.zip-builder"; path = ./../sources/c76q39xsl9myhy2a7id1wlqvl4zrlzmi-docbook-xml-4.2.zip-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/zxnbbhhrj6pq7qlp1nbhcb81n3gy5vw6-zipbomb-docbook-xml-4.2.zip.nix).out} ${(import ../store/5yj3dbvv2m0pbi7611cqwrs9ixy6qvgp-unzip-6.0.nix).out}";
}
