# Generated by guix-transfer
builtins.derivation {
  name = "nano-8.7.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-r9KHqmcsSLjhqT/bbGWIRT1SdRDZZoIraH8oNfDZhuk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/nano-8.7.tar.xz/sha256/1sc6v7q3aa3zd0mq4rnr21sm4ga5i1jnrnrzm7hvhj1ccym8glmg";
}
