# Generated by guix-transfer
builtins.derivation {
  name = "texlive-pgf-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/i97lsjrdjrls7l0flyny57aihsxj3xk2-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-pTqJnNyDk0HWuqRdobd4V01zgNigjTg8YiECMz3rbZo=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "165,58,137,156,220,131,147,65,214,186,164,93,161,183,120,87,77,115,128,216,160,141,56,60,98,33,2,51,61,235,109,154";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/generic/pgf/\" \"tex/context/third/pgf/basiclayer/\" \"tex/context/third/pgf/frontendlayer/\" \"tex/context/third/pgf/math/\" \"tex/context/third/pgf/systemlayer/\" \"tex/context/third/pgf/utilities/\" \"tex/generic/pgf/\" \"tex/latex/pgf/basiclayer/\" \"tex/latex/pgf/compatibility/\" \"tex/latex/pgf/doc/\" \"tex/latex/pgf/frontendlayer/\" \"tex/latex/pgf/math/\" \"tex/latex/pgf/systemlayer/\" \"tex/latex/pgf/utilities/\" \"tex/plain/pgf/basiclayer/\" \"tex/plain/pgf/frontendlayer/\" \"tex/plain/pgf/math/\" \"tex/plain/pgf/systemlayer/\" \"tex/plain/pgf/utilities/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).debug} ${(import ../store/qk9zgwdm7jg88a7fmw6nlp6zgdykazbw-subversion-1.14.5.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out}";
}
