# Generated by guix-transfer
builtins.derivation {
  name = "module-import-compiled";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''compile-modules''; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; }}"
  ];
  srcs = [
    (builtins.path { name = "build-utils.scm"; path = ./../sources/mcpxrl5ql7qyib48qn6g235balyhz7ym-build-utils.scm; })
    (builtins.path { name = "qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import"; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; })
    (builtins.path { name = "compile-modules"; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; })
  ];
  GUILE_WARN_DEPRECATED = "no";
  extensions = "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}";
  "module count" = "7";
  modules = "${builtins.path { name = ''qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import''; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; }}";
  "optimization level" = "1";
  preferLocalBuild = "1";
}
