# Generated by guix-transfer
builtins.derivation {
  name = "grep-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''grep-runtime-env-builder''; path = ./../sources/l98fw5anqsiqkxrpz9i8dvqly0gcbm00-grep-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "grep-runtime-env-builder"; path = ./../sources/l98fw5anqsiqkxrpz9i8dvqly0gcbm00-grep-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/qlnj387wxmddks8fvf5hypl8vadznw58-pcre2-10.42.nix).out} ${(import ../store/na2zrk23sfgzy9vn17xq67ggzqwsnz3c-grep-3.11.nix).out}";
}
