# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot0-2.20.1a";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-mesboot0-2.20.1a-builder''; path = ./../sources/bj1g2q55wj837859jkcywwcs8lzn6x7q-binutils-mesboot0-2.20.1a-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "binutils-mesboot0-2.20.1a-builder"; path = ./../sources/bj1g2q55wj837859jkcywwcs8lzn6x7q-binutils-mesboot0-2.20.1a-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/j3lzhxx8assiz7820cgg6j9a5lj8smv0-tcc-boot-0.9.27.nix).out} ${(import ../store/m91dc1vd1z4nq689hwv2ipf7yzbavyj2-binutils-2.20.1a.tar.xz.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/331ba5f179xy18hhafkd2cx35k33dpj7-make-mesboot0-3.80.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out}";
}
