# Generated by guix-transfer
builtins.derivation {
  name = "guile-pipe-0.0.0-0.0746ec3";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''f1ygy3nc6s4gyyp158m7q0ryvndfzaky-module-import''; path = ./../sources/l2icgkyb7gj82f4n2gsjc34x5byavnds-f1ygy3nc6s4gyyp158m7q0ryvndfzaky-module-import; }}"
    "-C"
    "${(import ../store/y6pisyk2sdpriagd0q7nm4za3bin44x6-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-pipe-0.0.0-0.0746ec3-builder''; path = ./../sources/ygdy9sjh5w66p8j19nszc9nswc316hb6-guile-pipe-0.0.0-0.0746ec3-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "guile-pipe-0.0.0-0.0746ec3-builder"; path = ./../sources/ygdy9sjh5w66p8j19nszc9nswc316hb6-guile-pipe-0.0.0-0.0746ec3-builder; })
    (builtins.path { name = "f1ygy3nc6s4gyyp158m7q0ryvndfzaky-module-import"; path = ./../sources/l2icgkyb7gj82f4n2gsjc34x5byavnds-f1ygy3nc6s4gyyp158m7q0ryvndfzaky-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out} ${(import ../store/zv6pid8hprjnlkcrfapxfb95ll888vyb-guile-pipe-0.0.0-0.0746ec3-checkout.nix).out}";
}
