# Generated by guix-transfer
builtins.derivation {
  name = "patch-2.7.6.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''patch-2.7.6.tar.xz-builder''; path = ./../sources/fy7bf2as5slmzdqh63wv78plqigba9rd-patch-2.7.6.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "patch-2.7.6.tar.xz-builder"; path = ./../sources/fy7bf2as5slmzdqh63wv78plqigba9rd-patch-2.7.6.tar.xz-builder; })
    (builtins.path { name = "patch-hurd-path-max.patch"; path = ./../sources/kkgdxnrv2sfb95r29wzqhx0j22x5p131-patch-hurd-path-max.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/fpxz2pycsvzaaf2wpq3ccivimvkvaw67-patch-2.7.6.tar.xz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out}";
}
