# Generated by guix-transfer
builtins.derivation {
  name = "kbd-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''kbd-runtime-env-builder''; path = ./../sources/yg2vwldwb4jxazhg46afq46mzpw43ahz-kbd-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "kbd-runtime-env-builder"; path = ./../sources/yg2vwldwb4jxazhg46afq46mzpw43ahz-kbd-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/w5b1np7ri8m7ci675bbn7dhgay75ghcr-zstd-1.5.6.nix).out} ${(import ../store/al585zfr2ydg7jn7dzzy2mjhndfmy7v2-bash-minimal-5.2.37.nix).out} ${(import ../store/3ywnviw7qj7r4aq7d3sbb1jsxxnarsa7-linux-pam-1.5.2.nix).out} ${(import ../store/6kjc8wxpk2g9fgdyfq6cphhy9v85ry57-kbd-2.5.1.nix).out} ${(import ../store/23iksirmjjs0mb8nxrg7mfdqdc05w9ak-xz-5.4.5.nix).out} ${(import ../store/rj26nciglg7qzilg4wjnmdp8lj7n38hb-bzip2-1.0.8.nix).out}";
}
