# Generated by guix-transfer
builtins.derivation {
  name = "gobject-introspection-1.82.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gobject-introspection-1.82.0.tar.zst-builder''; path = ./../sources/xn2ykr4jai177lc21da2iry4c086wr0c-gobject-introspection-1.82.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gobject-introspection-absolute-shlib-path.patch"; path = ./../sources/aws0r18pgm2hkmh45lklvm0bsia89wyx-gobject-introspection-absolute-shlib-path.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gobject-introspection-1.82.0.tar.zst-builder"; path = ./../sources/xn2ykr4jai177lc21da2iry4c086wr0c-gobject-introspection-1.82.0.tar.zst-builder; })
    (builtins.path { name = "gobject-introspection-cc.patch"; path = ./../sources/ddynp9a0kksp7dcjx4rzd6zdq0a9gmvy-gobject-introspection-cc.patch; })
    (builtins.path { name = "gobject-introspection-girepository.patch"; path = ./../sources/mfh2cd1d8rsl6989ydd0fijy8iw76ra8-gobject-introspection-girepository.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/8ykvqd0xajv7g7fj139cnlylfldnrqfi-gobject-introspection-1.82.0.tar.xz.nix).out}";
}
