# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot1-4.6.4";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot1-4.6.4-builder''; path = ./../sources/b6qprkv02vqawsacsazk75c561m8qsj3-gcc-mesboot1-4.6.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-boot-4.6.4.patch"; path = ./../sources/vvs3n0s0z06w3pmim66c1gbgngj1w34i-gcc-boot-4.6.4.patch; })
    (builtins.path { name = "gcc-mesboot1-4.6.4-builder"; path = ./../sources/b6qprkv02vqawsacsazk75c561m8qsj3-gcc-mesboot1-4.6.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/k4n2ncfcn82bv2mhvz1rj6794r264c33-gcc-g++-4.6.4.tar.gz.nix).out} ${(import ../store/xggzkkkiipw1wm6dv9cyizizdvywrab8-gcc-core-4.6.4.tar.gz.nix).out} ${(import ../store/7acbr2h8fcs2w4flc3fjrw91bl4k6d0b-gmp-4.3.2.tar.gz.nix).out} ${(import ../store/sjm0lzfypcbx3m38w3wx5n5fily3xw1i-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/nzx18n1kfil6d2scrh2fq6ipfk5rshx9-gcc-mesboot0-2.95.3.nix).out} ${(import ../store/riq6mqzhvnxpwx3wk1dfy7npl8kqz89l-make-mesboot-3.82.nix).out} ${(import ../store/znzjy8p744ccrwb95fahjcwpj3in9ffn-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/3h1ad9c87ql05kzfmxhiha8mh75skhcr-mpfr-2.4.2.tar.gz.nix).out} ${(import ../store/4x08lx6pl4khvpqkl9a1n3mf4mnrbjj4-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out} ${(import ../store/gxa2y5niwj6mjry1k8xwacpcsfjai4br-mpc-1.0.3.tar.gz.nix).out}";
}
