# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/pallets/click"; rev = "refs/tags/8.1.8"; hash = "sha256-pAAqf8jZbDfVZUoltwIFpov/1ys6HSYMyw3WV2qcE/M="; name = "python-click-8.1.8-checkout"; fetchSubmodules = false; }
