# Generated by guix-transfer
builtins.derivation {
  name = "gawk-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gawk-runtime-env-builder''; path = ./../sources/bcria19g9qwil62afrx4my8a7a9v5cc5-gawk-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "gawk-runtime-env-builder"; path = ./../sources/bcria19g9qwil62afrx4my8a7a9v5cc5-gawk-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/sd75dr2iv6aa6aicf84km8r6cqw0a523-bash-5.2.37.nix).out} ${(import ../store/pz6wraagjxmx41da5pnlx2wymz69qb4j-gawk-5.3.0.nix).out} ${(import ../store/y7wxw8iac4d7w2fvy7378v96kvc2qq2l-libsigsegv-2.14.nix).out}";
}
