# Generated by guix-transfer
builtins.derivation {
  name = "gcc-cross-boot0-wrapped-14.3.0";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-cross-boot0-wrapped-14.3.0-builder''; path = ./../sources/wrpqj0323z6ijacd6i2f1nm2lcsqcwij-gcc-cross-boot0-wrapped-14.3.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gcc-cross-boot0-wrapped-14.3.0-builder"; path = ./../sources/wrpqj0323z6ijacd6i2f1nm2lcsqcwij-gcc-cross-boot0-wrapped-14.3.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/16c66kpa8b7ffyfndwcwkvl4asa4ak25-gcc-cross-boot0-14.3.0.nix).out} ${(import ../store/1gnx4bx9mvxkc12hc91brkw5k36hvbjj-binutils-cross-boot0-2.44.nix).out} ${(import ../store/3chpzppcz6g5nv9p9w3bf7yyppg21pm0-bash-mesboot-5.2.37.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).out} ${(import ../store/v0bqkz3ga4yxiiwws5sada1wz0mzbndf-linux-libre-headers-6.12.17.nix).out}";
}
