# Generated by guix-transfer
builtins.derivation {
  name = "http-parser-2.9.4-1.ec8b5ee-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''http-parser-2.9.4-1.ec8b5ee-checkout-builder''; path = ./../sources/r5g7ja81wngf6dc4mms5ri1bnhkv3rgf-http-parser-2.9.4-1.ec8b5ee-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "http-parser-2.9.4-1.ec8b5ee-checkout-builder"; path = ./../sources/r5g7ja81wngf6dc4mms5ri1bnhkv3rgf-http-parser-2.9.4-1.ec8b5ee-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "http-parser-CVE-2020-8287.patch"; path = ./../sources/cwz49v7vijpyhs72824wrsldn6yc6kk2-http-parser-CVE-2020-8287.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/mc6bsqlr5a6nifln6zi6y4iiamj8jhdw-0001-url-treat-empty-port-as-default.patch.nix).out} ${(import ../store/bxgcrv843jf8p34db7y3ahc5w8raw20m-http-parser-2.9.4-1.ec8b5ee-checkout.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
