# Generated by guix-transfer
builtins.derivation {
  name = "perl-5.36.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''perl-5.36.0.tar.xz-builder''; path = ./../sources/x2crjv0b1a5hp5dr7xlw2k700b5cfxma-perl-5.36.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "perl-autosplit-default-time.patch"; path = ./../sources/4jd7mh8cpcj47i05gdj8c6vkrg8d7zjk-perl-autosplit-default-time.patch; })
    (builtins.path { name = "perl-no-sys-dirs.patch"; path = ./../sources/7r5j8g69z60c9slmf8m31kawhk2l4l1i-perl-no-sys-dirs.patch; })
    (builtins.path { name = "perl-reproducible-build-date.patch"; path = ./../sources/fhzg15wba2lf0syic8dgc0balj2fzw7f-perl-reproducible-build-date.patch; })
    (builtins.path { name = "perl-5.36.0.tar.xz-builder"; path = ./../sources/x2crjv0b1a5hp5dr7xlw2k700b5cfxma-perl-5.36.0.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/zj42rp8hgrjqkmrwbnb3p6snwygfql7v-perl-5.36.0.tar.gz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out}";
}
