# Generated by guix-transfer
builtins.derivation {
  name = "linux-6.12.62.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-E+LGhayPq13Zkt0QVzJVTa5RSu81DCqMdBjnt062LBM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/linux-6.12.62.tar.xz/sha256/04rcnr7bgrqqfj62l31mxx553bjdalr5f46xjbcmvawgmj2wdqhk";
}
