# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-deblob-6.12.62-gnu";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-lg6+hbscEI6738OL1TjCogALaL4UYphIIeN6v/30Cpk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/linux-libre-deblob-6.12.62-gnu/sha256/168aykyvyyp34549hqhlprl0n052q8wdb2y3vyxqw40wpf2vw3ln";
}
