# Generated by guix-transfer
builtins.derivation {
  name = "coreutils-boot0-9.1";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''coreutils-boot0-9.1-builder''; path = ./../sources/b7mllw0wifgi9zlis3s23p99qlxkrc9c-coreutils-boot0-9.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "coreutils-boot0-9.1-builder"; path = ./../sources/b7mllw0wifgi9zlis3s23p99qlxkrc9c-coreutils-boot0-9.1-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/pk4gwnc3fl5yyv3067wnvdaghd6r0nn9-gcc-mesboot-4.9.4.nix).out} ${(import ../store/1y8yylmfqhp3vbczriakvbmdqffp3hgh-coreutils-mesboot-9.1.nix).out} ${(import ../store/3chpzppcz6g5nv9p9w3bf7yyppg21pm0-bash-mesboot-5.2.37.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/3qlr64nvpxqabkwy8xh38vnhmb8bsxp0-glibc-mesboot-2.16.0.nix).out} ${(import ../store/dqfsx3csp0ys6gkrlkc9wjywq5b4yf3n-coreutils-9.1.tar.xz.nix).out} ${(import ../store/f3jv0abf796dvc16wjyzgh4ga4715j9r-gawk-mesboot-3.1.8.nix).out} ${(import ../store/33fhwbccw54ns3zrzwfqd5xf8dpk06l0-grep-mesboot-3.11.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/g6y4w2snrgl1ccip9bkcv1p9by9zld94-gcc-mesboot-wrapper-4.9.4.nix).out} ${(import ../store/riq6mqzhvnxpwx3wk1dfy7npl8kqz89l-make-mesboot-3.82.nix).out} ${(import ../store/sl7dfq8a1jnaa9pdg8bcikqmgyv30xd9-xz-mesboot-5.4.5.nix).out} ${(import ../store/4xj4pxakda4ghpl02fs6l47l0bfakcmh-sed-mesboot-4.8.nix).out} ${(import ../store/hwkx426jqrv4fxahg7kwassxr2fn8pq0-tar-mesboot-1.35.nix).out} ${(import ../store/k394ccmgcbfqy83b7hravh24m8b14mjm-make-boot0-4.4.1.nix).out} ${(import ../store/h91qgk3x4wcwlw20vfvws3c92fgqs274-binutils-mesboot-2.20.1a.nix).out}";
}
