# Generated by guix-transfer
builtins.derivation {
  name = "100gnu+freedo.patch";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BlR85I4Lko7BJxTy62dHYmaZGSsZi/aFrQsg1jvXacI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/100gnu+freedo.patch/sha256/1hk9swxxc80bmn2zd2qr5ccrjrk28xkypwhl4z0qx4hbivj7qm06";
}
