# Generated by guix-transfer
builtins.derivation {
  name = "tar-1.35.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''tar-1.35.tar.zst-builder''; path = ./../sources/0kzb2xwpc35c1r3x5jghhhaqbbywkk35-tar-1.35.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "tar-remove-wholesparse-check.patch"; path = ./../sources/ihbh0qnhi3xbqmsbi3qg45hvscrkrn6w-tar-remove-wholesparse-check.patch; })
    (builtins.path { name = "tar-skip-unreliable-tests.patch"; path = ./../sources/0sryxvbp3m4cln8ckpxpw0z7iy1fz1bd-tar-skip-unreliable-tests.patch; })
    (builtins.path { name = "tar-1.35.tar.zst-builder"; path = ./../sources/0kzb2xwpc35c1r3x5jghhhaqbbywkk35-tar-1.35.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/fhhcbkpzqrn1gzgd8fj954sbk2aawinv-tar-1.35.tar.xz.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
