# Generated by guix-transfer
builtins.derivation {
  name = "texlive-tex-gyre-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/i97lsjrdjrls7l0flyny57aihsxj3xk2-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/89jxyi7xx1xqz3nlz9s1rzbk0anwr9xk-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-mBY5n404mdcm4THGsjggo1DQiblcvuDWP2SDrbJ5yC4=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "152,22,57,159,141,56,153,215,38,225,49,198,178,56,32,163,80,208,137,185,92,190,224,214,63,100,131,173,178,121,200,46";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/fonts/tex-gyre/\" \"fonts/afm/public/tex-gyre/\" \"fonts/enc/dvips/tex-gyre/\" \"fonts/map/dvips/tex-gyre/\" \"fonts/opentype/public/tex-gyre/\" \"fonts/tfm/public/tex-gyre/\" \"fonts/type1/public/tex-gyre/\" \"source/fonts/tex-gyre/\" \"tex/latex/tex-gyre/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).debug} ${(import ../store/qk9zgwdm7jg88a7fmw6nlp6zgdykazbw-subversion-1.14.5.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out}";
}
