# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot-wrapper-4.9.4";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot-wrapper-4.9.4-builder''; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-mesboot-wrapper-4.9.4-builder"; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/pk4gwnc3fl5yyv3067wnvdaghd6r0nn9-gcc-mesboot-4.9.4.nix).out} ${(import ../store/3qlr64nvpxqabkwy8xh38vnhmb8bsxp0-glibc-mesboot-2.16.0.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out}";
}
