# Generated by guix-transfer
builtins.derivation {
  name = "util-linux-2.40.4.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''util-linux-2.40.4.tar.zst-builder''; path = ./../sources/j1zvnznmrxvc37six6dpwl6wgw9sc5jh-util-linux-2.40.4.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "util-linux-tests.patch"; path = ./../sources/f8nn9a0kj7wlxzr5i4pafyj5vk7n5vsn-util-linux-tests.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "util-linux-2.40.4.tar.zst-builder"; path = ./../sources/j1zvnznmrxvc37six6dpwl6wgw9sc5jh-util-linux-2.40.4.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/7daimxvdkifxi7ajc2zg19z4c1y0gvac-util-linux-2.40.4.tar.xz.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
