# Generated by guix-transfer
builtins.derivation {
  name = "time-1.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+6zwyB5iQp3z4zvaTO44dWYE8Y4B2XczjiMwaj47Uh4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/time-1.9.tar.gz/sha256/07jj7cz6lc13iqrpgn81ivqh8rkm73p4rnivwgrrshk23v4g1b7v";
}
