# Generated by guix-transfer
builtins.derivation {
  name = "util-linux-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''util-linux-runtime-env-builder''; path = ./../sources/6icvcbp806sv1yrayvw07g48i5ild3g0-util-linux-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "util-linux-runtime-env-builder"; path = ./../sources/6icvcbp806sv1yrayvw07g48i5ild3g0-util-linux-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/ls8wpvkps6yn0w1lgwhz6vrhlgp288cv-ncurses-6.2.20210619.nix).out} ${(import ../store/4dmn9njb6n1zxaxvzfxf6aajsywgg40f-file-5.46.nix).out} ${(import ../store/8xzicbhsyfv5dxjxcl8m709x37p86gnc-sqlite-3.39.3.nix).out} ${(import ../store/jy3x6qsmfvhymrxf4hpzx0fvyxmqpfhl-util-linux-2.40.4.nix).out} ${(import ../store/hsfkwglj2qzj7mlibrr34ga0rwspf53p-zlib-1.3.1.nix).out}";
}
