# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-arm-export-__sync_icache_dcache.patch";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Lg26v0VcbTEV/uk7NmmXvyZ9WeGnH4sWsc79qS501sU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/linux-libre-arm-export-__sync_icache_dcache.patch/sha256/1ifnfhpakzffn4b8n7x7w5cps9mzjxlkcfz9zqak2vaw8nzvl39f";
}
