# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-boot3-0";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-boot3-0-builder''; path = ./../sources/9fyzadmxd1mz8wmvak4ls98lggazpy5w-ld-wrapper-boot3-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "ld-wrapper-boot3-0-builder"; path = ./../sources/9fyzadmxd1mz8wmvak4ls98lggazpy5w-ld-wrapper-boot3-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/3chpzppcz6g5nv9p9w3bf7yyppg21pm0-bash-mesboot-5.2.37.nix).out} ${(import ../store/7lczvd4rfk1nahv0af9zknkxm6jj3js9-binutils-2.44.nix).out}";
}
