# Generated by guix-transfer
builtins.derivation {
  name = "iproute2-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''iproute2-runtime-env-builder''; path = ./../sources/pnz8217kdk1mvpyzfb104v81znrv7xaa-iproute2-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "iproute2-runtime-env-builder"; path = ./../sources/pnz8217kdk1mvpyzfb104v81znrv7xaa-iproute2-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/n0dwn27fiwfqzkq5synm85rb7s7hy5i7-bdb-6.2.32.nix).out} ${(import ../store/ra5wz58fsdn5mvky56krb8hdw8mp3c9l-libmnl-1.0.5.nix).out} ${(import ../store/ncxnfarnl5jsi5zpk33pb6gwal0sb9ml-iptables-1.8.11.nix).out} ${(import ../store/ml9z0fklw5qgr1nzrwjd0mh6zsdd4rs8-iproute2-6.4.0.nix).out}";
}
