# Generated by guix-transfer
builtins.derivation {
  name = "module-import-compiled";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''compile-modules''; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; }}"
  ];
  srcs = [
    (builtins.path { name = "build-utils.scm"; path = ./../sources/mcpxrl5ql7qyib48qn6g235balyhz7ym-build-utils.scm; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
    (builtins.path { name = "compile-modules"; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; })
  ];
  GUILE_WARN_DEPRECATED = "no";
  extensions = "${(import ../store/gf5qc3p2s4nly9slsihfyq3vsnhp2y4w-guile-json-4.7.3.nix).out} ${(import ../store/ayhfyvl5v8b8rgfzqwhhxpby6q9ffnjs-guile-gnutls-5.0.1.nix).out} ${(import ../store/i68156y0clmzzpndw6cqzk6grkblv24y-guile-lzlib-0.3.0.nix).out}";
  "module count" = "14";
  modules = "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}";
  "optimization level" = "1";
  preferLocalBuild = "1";
}
