# Generated by guix-transfer
builtins.derivation {
  name = "findutils-4.10.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''findutils-4.10.0.tar.xz-builder''; path = ./../sources/zhhbcf37scpjyrqx68x0h3q6wi2md7ha-findutils-4.10.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "findutils-localstatedir.patch"; path = ./../sources/xn0wb7d2k1v2yjkby7x885w77vfsdxjm-findutils-localstatedir.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "findutils-4.10.0.tar.xz-builder"; path = ./../sources/zhhbcf37scpjyrqx68x0h3q6wi2md7ha-findutils-4.10.0.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/axs3mf1kb3z69mbhzplsydwl3m3smkch-findutils-4.10.0.tar.xz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out}";
}
