# Generated by guix-transfer
builtins.derivation {
  name = "tcc-boot-0.9.27";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''tcc-boot-0.9.27-builder''; path = ./../sources/ysx77pr0i7hwr5f3a7m6n59rpl8frfda-tcc-boot-0.9.27-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "tcc-boot-0.9.27-builder"; path = ./../sources/ysx77pr0i7hwr5f3a7m6n59rpl8frfda-tcc-boot-0.9.27-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/4q8ia7lj3zdh0yd18ld55fkpfmpbpnnl-mes-boot-0.25.1.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/331ba5f179xy18hhafkd2cx35k33dpj7-make-mesboot0-3.80.nix).out} ${(import ../store/fll545ah3yg937kwhsfcgnz1ffacxq5b-tcc-boot0-0.9.26-1149-g46a75d0c.nix).out} ${(import ../store/n41cc6hx4kkxnc2bagnamf4nhzj4ncd6-tcc-0.9.27.tar.bz2.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out}";
}
