# Generated by guix-transfer
builtins.derivation {
  name = "g-golf-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''g-golf-runtime-env-builder''; path = ./../sources/0645mkvhp3v7i5i63q6sjd00r7qmjd99-g-golf-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "g-golf-runtime-env-builder"; path = ./../sources/0645mkvhp3v7i5i63q6sjd00r7qmjd99-g-golf-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/jy3x6qsmfvhymrxf4hpzx0fvyxmqpfhl-util-linux-2.40.4.nix).lib} ${(import ../store/qgrbns4vda7b4jh05a18m5l8y1rmyznc-g-golf-0.8.2.nix).out} ${(import ../store/7n5nmvbcky59vhp7kkhy39y0w80g9l4w-gobject-introspection-1.82.0.nix).out} ${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/rj00swz82v153kjvhna9pqrgnazykp2a-libffi-3.4.6.nix).out} ${(import ../store/qlnj387wxmddks8fvf5hypl8vadznw58-pcre2-10.42.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/1gvv1q7q7nlv1b0piggyv6p3h7cazhvl-glib-2.83.3.nix).out} ${(import ../store/n34vvis15qy96fvl88dcd8y400wf8pwd-guile-lib-0.2.8.1.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out} ${(import ../store/hsfkwglj2qzj7mlibrr34ga0rwspf53p-zlib-1.3.1.nix).out}";
}
