# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/libbpf/libbpf"; rev = "refs/tags/v1.5.0"; hash = "sha256-0PadA9OppNGmgSTLi8sXrh3syxPVkqrnTkBr8cyp+Ug="; name = "libbpf-1.5.0-checkout"; fetchSubmodules = false; }
