# Generated by guix-transfer
builtins.derivation {
  name = "shadow-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''shadow-runtime-env-builder''; path = ./../sources/01sy88vljsq9yxhd2rg3nccxa64mkd2z-shadow-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "shadow-runtime-env-builder"; path = ./../sources/01sy88vljsq9yxhd2rg3nccxa64mkd2z-shadow-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/x8wnhf1f9dq7daq30dasl09m26mj4cm1-libxcrypt-4.4.38.nix).out} ${(import ../store/hzi7w1lfvwcbm1xfw6dvris7pgsksvi3-shadow-4.13.nix).out} ${(import ../store/3ywnviw7qj7r4aq7d3sbb1jsxxnarsa7-linux-pam-1.5.2.nix).out}";
}
