# Generated by guix-transfer
builtins.derivation {
  name = "perl-5.36.0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/5gxvwq166nhm2wjqrfa5vzvg1nz7wna8-module-import-compiled.nix).out}"
    "${builtins.path { name = ''perl-5.36.0-builder''; path = ./../sources/riwc7j0flnyvqwjqxly3knl8h78r777m-perl-5.36.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "perl-5.36.0-builder"; path = ./../sources/riwc7j0flnyvqwjqxly3knl8h78r777m-perl-5.36.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/gba0pl3qwvzwwprccdrwqmn2mk90dv4f-gcc-14.3.0.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).out} ${(import ../store/p3433p8apcjvic6599dgwhjhjl021h1s-file-5.46.nix).out} ${(import ../store/xhc955ds83dwm39hffzy9iz7nhzhqirb-bash-minimal-5.2.37.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/0wwg2ganpbif26wqz4kfllf323s2zf90-gawk-5.3.0.nix).out} ${(import ../store/rp9hiq87ggb5gj04s2xv9rqrj7r37z3k-ld-wrapper-0.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/v0bqkz3ga4yxiiwws5sada1wz0mzbndf-linux-libre-headers-6.12.17.nix).out} ${(import ../store/pqkx49kj6b9v9sfc79pbisrylc0rwq8g-coreutils-9.1.nix).out} ${(import ../store/7lczvd4rfk1nahv0af9zknkxm6jj3js9-binutils-2.44.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/fjb6sh02qcv17h2zqifb2hwaf3klhrky-make-4.4.1.nix).out} ${(import ../store/yypwx3p2rzfffld50b55z1c1qsjma4fx-diffutils-3.12.nix).out} ${(import ../store/bvl4ill7rbq0rnic5fld07ra5k69simc-grep-3.11.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/pa5q29gjzppzxhar028g228j0p4xi4a2-perl-5.36.0.tar.zst.nix).out} ${(import ../store/hb1p3098wgrblsz08jzyn1g81a35lx44-sed-4.9.nix).out} ${(import ../store/rp8yv6yxmdvqzx5hcl4g4jbzhga4k6iv-findutils-4.10.0.nix).out} ${(import ../store/rs0qwdssy231vjqhcn6q81y6nx17bk3q-glibc-2.41.nix).static}";
}
