# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/htop-dev/htop"; rev = "refs/tags/3.4.1"; hash = "sha256-fVqQwXbJus2IVE1Bzf3yJJpKK4qcZN/SCTX1XYkiHhU="; name = "htop-3.4.1-checkout"; fetchSubmodules = false; }
