# Generated by guix-transfer
builtins.derivation {
  name = "make-4.4.1.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''make-4.4.1.tar.xz-builder''; path = ./../sources/rl1vpjw0li89wn4y22nfv19y0adg0gzp-make-4.4.1.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "make-4.4.1.tar.xz-builder"; path = ./../sources/rl1vpjw0li89wn4y22nfv19y0adg0gzp-make-4.4.1.tar.xz-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "make-impure-dirs.patch"; path = ./../sources/a4q7d2x00cs61iq0g2dnh97gpinqga0m-make-impure-dirs.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/k246d61hn5kbxdc619j8imafcxd4jsb3-make-4.4.1.tar.gz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out}";
}
