# Generated by guix-transfer
builtins.derivation {
  name = "gpm-1.20.7.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gpm-1.20.7.tar.zst-builder''; path = ./../sources/jzkkgq0wmyqhms6kdqgfqfbqrrx7801r-gpm-1.20.7.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gpm-glibc-2.26.patch"; path = ./../sources/bxircy9v4ij09dviw01w2fscwhxi2vz6-gpm-glibc-2.26.patch; })
    (builtins.path { name = "gpm-1.20.7.tar.zst-builder"; path = ./../sources/jzkkgq0wmyqhms6kdqgfqfbqrrx7801r-gpm-1.20.7.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/3h4vhx1b5g42w4q7y5w21d65k7y70g5f-gpm-1.20.7.tar.bz2.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
