# Generated by guix-transfer
builtins.derivation {
  name = "htop-minimal-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''htop-minimal-runtime-env-builder''; path = ./../sources/y5nv4nvvgc9iv9n7wdzdwh48800nkb6d-htop-minimal-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "htop-minimal-runtime-env-builder"; path = ./../sources/y5nv4nvvgc9iv9n7wdzdwh48800nkb6d-htop-minimal-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/40r83x1zcxm8rvsd6ph4kla3l4xii65v-htop-minimal-3.4.1.nix).out} ${(import ../store/ls8wpvkps6yn0w1lgwhz6vrhlgp288cv-ncurses-6.2.20210619.nix).out}";
}
