# Generated by guix-transfer
builtins.derivation {
  name = "gash-boot-0.3.1";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''n4vnmaaac03xaviwzx2544h625x1qq3i-module-import''; path = ./../sources/30saz8qghpd87bp6bbj9c8w7mvq7zwbx-n4vnmaaac03xaviwzx2544h625x1qq3i-module-import; }}"
    "-C"
    "${(import ../store/y1gfa8yssnfd8dlsr2nwf4wmivrbs9vz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gash-boot-0.3.1-builder''; path = ./../sources/zaj8lf3iwhdj81q1fl3phyg7n8g85nxh-gash-boot-0.3.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gash-boot-0.3.1-builder"; path = ./../sources/zaj8lf3iwhdj81q1fl3phyg7n8g85nxh-gash-boot-0.3.1-builder; })
    (builtins.path { name = "n4vnmaaac03xaviwzx2544h625x1qq3i-module-import"; path = ./../sources/30saz8qghpd87bp6bbj9c8w7mvq7zwbx-n4vnmaaac03xaviwzx2544h625x1qq3i-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/5xkrhr0g8i8qq6zz0gaddl05yvl5i2d5-gash-0.3.1.tar.gz.nix).out}";
}
