# Generated by guix-transfer
builtins.derivation {
  name = "gcc-14.3.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-14.3.0.tar.xz-builder''; path = ./../sources/sxw6gmzy79wbavmiqh55cdfc6wjv1vq5-gcc-14.3.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gcc-5.0-libvtv-runpath.patch"; path = ./../sources/q9qlyld3rch8kd3qrxcss1r2p1fhdv95-gcc-5.0-libvtv-runpath.patch; })
    (builtins.path { name = "gcc-12-strmov-store-file-names.patch"; path = ./../sources/ydfd42mc58s9glr4wgf6jdvrfr52bnsw-gcc-12-strmov-store-file-names.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gcc-14.3.0.tar.xz-builder"; path = ./../sources/sxw6gmzy79wbavmiqh55cdfc6wjv1vq5-gcc-14.3.0.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/l1kl4rjnjc8skybjykirchx5a8xlzvpd-gcc-14.3.0.tar.xz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out} ${(import ../store/faw5ylib145zhgsfv5znf22gx9pigb0v-coreutils-boot0-9.1.nix).out}";
}
