# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/NetworkConfiguration/openresolv"; rev = "refs/tags/v3.13.2"; hash = "sha256-rpfzAIzuiO+QTFhN+tHND+OQOyX/GUPvLLX3CSSwqA4="; name = "openresolv-3.13.2-checkout"; fetchSubmodules = false; }
