# Generated by guix-transfer
builtins.derivation {
  name = "libstdc++-headers-13.3.0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''libstdc++-headers-13.3.0-builder''; path = ./../sources/pcpdxh1lj72g6g2cfnj83i2zvly4yj74-libstdc++-headers-13.3.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libstdc++-headers-13.3.0-builder"; path = ./../sources/pcpdxh1lj72g6g2cfnj83i2zvly4yj74-libstdc++-headers-13.3.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/16sw99hhiiq3xd2a2ydq1zn0sg2dsnkg-libstdc++-13.3.0.nix).out} ${(import ../store/qj0khvmnm7ir5pmj0qp5zclrjkw6l88s-gcc-13.3.0.tar.zst.nix).out}";
}
