# Generated by guix-transfer
builtins.derivation {
  name = "perl-5.36.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''perl-5.36.0.tar.zst-builder''; path = ./../sources/sr8bp78rfq3k4ldnc8dri2dfmvr4zi65-perl-5.36.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "perl-autosplit-default-time.patch"; path = ./../sources/4jd7mh8cpcj47i05gdj8c6vkrg8d7zjk-perl-autosplit-default-time.patch; })
    (builtins.path { name = "perl-5.36.0.tar.zst-builder"; path = ./../sources/sr8bp78rfq3k4ldnc8dri2dfmvr4zi65-perl-5.36.0.tar.zst-builder; })
    (builtins.path { name = "perl-no-sys-dirs.patch"; path = ./../sources/7r5j8g69z60c9slmf8m31kawhk2l4l1i-perl-no-sys-dirs.patch; })
    (builtins.path { name = "perl-reproducible-build-date.patch"; path = ./../sources/fhzg15wba2lf0syic8dgc0balj2fzw7f-perl-reproducible-build-date.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/zj42rp8hgrjqkmrwbnb3p6snwygfql7v-perl-5.36.0.tar.gz.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
