# Generated by guix-transfer
builtins.derivation {
  name = "numpy-1.26.4.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''numpy-1.26.4.tar.zst-builder''; path = ./../sources/8a6ps1abr0r7fracv81j9jr9vw3y5fpa-numpy-1.26.4.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "numpy-1.26.4.tar.zst-builder"; path = ./../sources/8a6ps1abr0r7fracv81j9jr9vw3y5fpa-numpy-1.26.4.tar.zst-builder; })
    (builtins.path { name = "python-numpy-gcc-14.patch"; path = ./../sources/cyq3s0y5662afd3bmqa5gddv46017rd1-python-numpy-gcc-14.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/advr42rsy27cz7zfdllvnd2l7kqpa83l-gzip-1.14.nix).out} ${(import ../store/kia3x802l19g1n9fw6q80v7qzk5x6mh4-numpy-1.26.4.tar.gz.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
