# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/NetworkConfiguration/dhcpcd"; rev = "refs/tags/v10.3.0"; hash = "sha256-XbXZkws1eHvN7OEq7clq2kziwwdk04lNrWbJ9RdHExU="; name = "dhcpcd-10.3.0-checkout"; fetchSubmodules = false; }
