# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot-4.9.4";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/diqk4gx5imb7s5zxhd35p10mf6ny5dms-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot-4.9.4-builder''; path = ./../sources/x35ckbxc2zc58xrqjppk7aningjgh7p6-gcc-mesboot-4.9.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-boot-4.6.4.patch"; path = ./../sources/vvs3n0s0z06w3pmim66c1gbgngj1w34i-gcc-boot-4.6.4.patch; })
    (builtins.path { name = "gcc-mesboot-4.9.4-builder"; path = ./../sources/x35ckbxc2zc58xrqjppk7aningjgh7p6-gcc-mesboot-4.9.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/99mdvv887nhpcwb4qmx4jrdgd341qglg-glibc-headers-mesboot-2.16.0.nix).out} ${(import ../store/7acbr2h8fcs2w4flc3fjrw91bl4k6d0b-gmp-4.3.2.tar.gz.nix).out} ${(import ../store/sjm0lzfypcbx3m38w3wx5n5fily3xw1i-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/n4ki4lsi7c2br433pyp21l131v2japvd-patch-mesboot-2.5.9.nix).out} ${(import ../store/l9ik5w1drp05ia01p2mszbrf1w4jps98-gcc-4.9.4.tar.xz.nix).out} ${(import ../store/3qlr64nvpxqabkwy8xh38vnhmb8bsxp0-glibc-mesboot-2.16.0.nix).out} ${(import ../store/f3jv0abf796dvc16wjyzgh4ga4715j9r-gawk-mesboot-3.1.8.nix).out} ${(import ../store/zd2i2h8253717a2n4jm6dkc6y5k219ja-gash-utils-boot-0.2.0.nix).out} ${(import ../store/9wj4yd6yjgj825kvn71g68v3kb0x53vz-bootar-1b.nix).out} ${(import ../store/bjv98x503w425i4r4bssyz8s6q8pfbp8-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/jk514j6z3gxdkd9zllr794hhlb6vdvsm-gzip-mesboot-1.2.4.nix).out} ${(import ../store/riq6mqzhvnxpwx3wk1dfy7npl8kqz89l-make-mesboot-3.82.nix).out} ${(import ../store/3h1ad9c87ql05kzfmxhiha8mh75skhcr-mpfr-2.4.2.tar.gz.nix).out} ${(import ../store/mpbw1djn31ab6f47iqcbr9n5i0y04k1b-gash-boot-0.3.1.nix).out} ${(import ../store/h91qgk3x4wcwlw20vfvws3c92fgqs274-binutils-mesboot-2.20.1a.nix).out} ${(import ../store/gxa2y5niwj6mjry1k8xwacpcsfjai4br-mpc-1.0.3.tar.gz.nix).out} ${(import ../store/7bln0rdkm8m3g6a2yr72rm4ja4gn01w1-gcc-mesboot1-wrapper-4.6.4.nix).out}";
}
