# Generated by guix-transfer
builtins.derivation {
  name = "guile-ics-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-ics-runtime-env-builder''; path = ./../sources/j57yrd57xvwxp2br6m63j38zhdga7iaj-guile-ics-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "guile-ics-runtime-env-builder"; path = ./../sources/j57yrd57xvwxp2br6m63j38zhdga7iaj-guile-ics-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/nansdgpbgir2v8razzqzpwkwg8lv8bhj-guile-dsv-0.8.0.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/jhhg3vy67rzx9i1d7qk9fr66dkkwviqj-guile-ics-0.7.0.nix).out} ${(import ../store/n34vvis15qy96fvl88dcd8y400wf8pwd-guile-lib-0.2.8.1.nix).out} ${(import ../store/5hbj22aib05nhxkhv122hxwnjkiqm2sm-guile-smc-0.6.4.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out}";
}
