# Generated by guix-transfer
builtins.derivation {
  name = "docbook-5.0.1.zip";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-evnfRSQQ4DWjcHiD5DA5tAYvCdwvSfLphto+TAOG48c=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/docbook-5.0.1.zip/sha256/1iz3hq1lqgnshvlz4j9gvh4jy1ml74qf90vqf2ikbq0h4i2xzybs";
}
