# Generated by guix-transfer
builtins.derivation {
  name = "openresolv-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''openresolv-runtime-env-builder''; path = ./../sources/wpaxg3y36jp37my3s2vpj76zqrn8x5vx-openresolv-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "openresolv-runtime-env-builder"; path = ./../sources/wpaxg3y36jp37my3s2vpj76zqrn8x5vx-openresolv-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/m4d2dvmry7qq6giibrc87pifm902rk88-coreutils-minimal-9.1.nix).out} ${(import ../store/b3pfm27d6i518vi6z8bny14i6p0hjpf4-openresolv-3.13.2.nix).out}";
}
