# Generated by guix-transfer
builtins.derivation {
  name = "font-google-material-design-icons-4.0.0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''8j2l80b4qag95x6vrgx775yclwriqgvf-module-import''; path = ./../sources/l6alqhki8p8png07xsfbbd31g215d5fb-8j2l80b4qag95x6vrgx775yclwriqgvf-module-import; }}"
    "-C"
    "${(import ../store/d82g6lmf4xp8v312qjl8hbapxy5kzxml-module-import-compiled.nix).out}"
    "${builtins.path { name = ''font-google-material-design-icons-4.0.0-builder''; path = ./../sources/zp28a7jqd053lghk6l0z9cs7y2s5lk5q-font-google-material-design-icons-4.0.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "8j2l80b4qag95x6vrgx775yclwriqgvf-module-import"; path = ./../sources/l6alqhki8p8png07xsfbbd31g215d5fb-8j2l80b4qag95x6vrgx775yclwriqgvf-module-import; })
    (builtins.path { name = "font-google-material-design-icons-4.0.0-builder"; path = ./../sources/zp28a7jqd053lghk6l0z9cs7y2s5lk5q-font-google-material-design-icons-4.0.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/5yj3dbvv2m0pbi7611cqwrs9ixy6qvgp-unzip-6.0.nix).out} ${(import ../store/6lxw5qj70xnj5qf9lvlb8ffzydz5nwva-gzip-1.14.nix).out} ${(import ../store/xma46m7h6d6sfy3z6hrm45wlfhl4pysr-tar-1.35.nix).out} ${(import ../store/23iksirmjjs0mb8nxrg7mfdqdc05w9ak-xz-5.4.5.nix).out} ${(import ../store/rj26nciglg7qzilg4wjnmdp8lj7n38hb-bzip2-1.0.8.nix).out} ${(import ../store/xj4zkq52s2hxzn4s905nfq8hr257i23v-font-google-material-design-icons-4.0.0-checkout.nix).out}";
}
