# Generated by guix-transfer
builtins.derivation {
  name = "attr-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''attr-runtime-env-builder''; path = ./../sources/lb1wvi6a2pxzn81yy2fwlvbj4fnlgks4-attr-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "attr-runtime-env-builder"; path = ./../sources/lb1wvi6a2pxzn81yy2fwlvbj4fnlgks4-attr-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/kpb781zr9m8qbfxks1826ridkcw5j9w5-perl-5.36.0.nix).out} ${(import ../store/5zy2lhwi10xg8x3dq3jkkp12b0yy43da-attr-2.5.1.nix).out}";
}
