# Generated by guix-transfer
builtins.derivation {
  name = "gtk+-3.24.51-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gtk+-3.24.51-checkout-builder''; path = ./../sources/aj9dgf9gdpkw596iwnpqzngiv8s6qbcr-gtk+-3.24.51-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gtk+-3.24.51-checkout-builder"; path = ./../sources/aj9dgf9gdpkw596iwnpqzngiv8s6qbcr-gtk+-3.24.51-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gtk3-respect-GUIX_GTK3_IM_MODULE_FILE.patch"; path = ./../sources/l6ywab3vlf1g1braymslapa82dfvvi6x-gtk3-respect-GUIX_GTK3_IM_MODULE_FILE.patch; })
    (builtins.path { name = "gtk3-respect-GUIX_GTK3_PATH.patch"; path = ./../sources/rs2h9kbffx7kyp3q4wjw191sra4zn073-gtk3-respect-GUIX_GTK3_PATH.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/25v4nag72x6nvq2f0zgfhi91mhyyll8v-gtk+-3.24.51-checkout.nix).out} ${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
