# Generated by guix-transfer
builtins.derivation {
  name = "kmod-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''kmod-runtime-env-builder''; path = ./../sources/dy8fjv5x4szc481qspn0fchlqs4xkwlc-kmod-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "kmod-runtime-env-builder"; path = ./../sources/dy8fjv5x4szc481qspn0fchlqs4xkwlc-kmod-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/mavc1iybbfrj6z7picl4y5cblbp1ckdp-kmod-29.nix).out} ${(import ../store/23iksirmjjs0mb8nxrg7mfdqdc05w9ak-xz-5.4.5.nix).out} ${(import ../store/w5b1np7ri8m7ci675bbn7dhgay75ghcr-zstd-1.5.6.nix).lib} ${(import ../store/hsfkwglj2qzj7mlibrr34ga0rwspf53p-zlib-1.3.1.nix).out}";
}
