# Generated by guix-transfer
builtins.derivation {
  name = "python-wrapper-3.11.14";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''python-wrapper-3.11.14-builder''; path = ./../sources/76zxx8dshrv73f93zi86hf8xh4nxfc3x-python-wrapper-3.11.14-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "python-wrapper-3.11.14-builder"; path = ./../sources/76zxx8dshrv73f93zi86hf8xh4nxfc3x-python-wrapper-3.11.14-builder; })
    (builtins.path { name = "sitecustomize.py"; path = ./../sources/sm310qy71q4i1s4rn0a5a29ryyiydvd4-sitecustomize.py; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/5yj3dbvv2m0pbi7611cqwrs9ixy6qvgp-unzip-6.0.nix).out} ${(import ../store/sd75dr2iv6aa6aicf84km8r6cqw0a523-bash-5.2.37.nix).out} ${(import ../store/a1xqv8kpnkcqqimbn7ym4qmqy0lyyzf2-tzdata-2025a.nix).out} ${(import ../store/jbfqnwdai7lyxs9l8n3wcf7saa87cj8g-zip-3.0.nix).out} ${(import ../store/j97jw7305ic7iji0d29qdx10n669iq1h-pkg-config-0.29.2.nix).out} ${(import ../store/41jsrkn9744bjm92qzzfv2kkxr5s07im-python-3.11.14.nix).out}";
}
