# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-0-builder''; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper-0-builder"; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; })
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/gbiz1zhyjbvyh37j3mii7d3mgz6z0k1s-libunistring-1.3.nix).out} ${(import ../store/xhc955ds83dwm39hffzy9iz7nhzhqirb-bash-minimal-5.2.37.nix).out} ${(import ../store/7lczvd4rfk1nahv0af9zknkxm6jj3js9-binutils-2.44.nix).out} ${(import ../store/c0ddmszk945a4wr0v6cvgrw1pzwq77qq-libgc-8.2.8.nix).out}";
}
