# Generated by guix-transfer
builtins.derivation {
  name = "e2fsprogs-1.47.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-CCQuZMoOgZTZwcqtSXYrGSCaBjGBmbY850rk7y105jw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/e2fsprogs-1.47.2.tar.xz/sha256/0g76fhnyzr2awwybd6c16439l80r5dv4kbfaq7cr908fr9j2w908";
}
