# Generated by guix-transfer
builtins.derivation {
  name = "libstdc++-headers-14.3.0";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''libstdc++-headers-14.3.0-builder''; path = ./../sources/j6i6wlwddacgh3h5hyd09p81i7xpp8dp-libstdc++-headers-14.3.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libstdc++-headers-14.3.0-builder"; path = ./../sources/j6i6wlwddacgh3h5hyd09p81i7xpp8dp-libstdc++-headers-14.3.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/bj7lbmdc99jb0lcj9pkypm76b15143pn-gcc-14.3.0.tar.zst.nix).out} ${(import ../store/hc5dr72jrvikdxk5bamr03hm8q9ph4hy-libstdc++-14.3.0.nix).out}";
}
