# Generated by guix-transfer
builtins.derivation {
  name = "guile-bootstrap-2.0";
  system = "x86_64-linux";
  builder = "${(import ../store/sg2m0sfqq2qj7pwiz02zhri96xxdwyz6-bash.nix).out}";
  args = [
    "${builtins.path { name = ''build-bootstrap-guile.sh''; path = ./../sources/sk3a7ng2j22ybsyh7jyipjdfa4mqls4c-build-bootstrap-guile.sh; }}"
  ];
  srcs = [
    (builtins.path { name = "build-bootstrap-guile.sh"; path = ./../sources/sk3a7ng2j22ybsyh7jyipjdfa4mqls4c-build-bootstrap-guile.sh; })
  ];
  GUILE_TARBALL = "${(import ../store/16fga22l3fw6p2a0ykyi8w41vmgbn2s0-guile-2.0.9.tar.xz.nix).out}";
  __phantom_deps = "${(import ../store/vaqbvb45b8asl4ahw4wjj9nn3vrrpdf1-tar.nix).out} ${(import ../store/swplmbf0wrs1vlviid7gglvf4ykafci3-mkdir.nix).out} ${(import ../store/8yfxma06bb92ivhkc4mqg3ichbsljxkv-xz.nix).out}";
}
