# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://codeberg.org/guile/fibers"; rev = "refs/tags/v1.4.2"; hash = "sha256-iK5S2pjGqpslkR9mgYVorulb6K5PdMRyrWVuXP5nAGI="; name = "guile-fibers-1.4.2-checkout"; fetchSubmodules = false; }
