# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-headers-bootstrap-0";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''linux-libre-headers-bootstrap-0-builder''; path = ./../sources/016ms4z2301gwygw9g8g83k3kad1mwh4-linux-libre-headers-bootstrap-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "linux-libre-headers-bootstrap-0-builder"; path = ./../sources/016ms4z2301gwygw9g8g83k3kad1mwh4-linux-libre-headers-bootstrap-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/1sl49hv0800fq7nqh4lb3v0ky3ydh9wa-linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz.nix).out} ${(import ../store/vaqbvb45b8asl4ahw4wjj9nn3vrrpdf1-tar.nix).out} ${(import ../store/8yfxma06bb92ivhkc4mqg3ichbsljxkv-xz.nix).out}";
}
