# Generated by guix-transfer
builtins.derivation {
  name = "curl-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''curl-runtime-env-builder''; path = ./../sources/h6qmhgn023dg6xwh9ym29f4pyq4l1n62-curl-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "curl-runtime-env-builder"; path = ./../sources/h6qmhgn023dg6xwh9ym29f4pyq4l1n62-curl-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/plwy702aas07vcngxb16270q1hiaj028-gmp-6.3.0.nix).out} ${(import ../store/sa4hbf0lgdb61riffaaknmc7jlh8pa0h-gnutls-3.8.3.nix).out} ${(import ../store/5igf10srni7mw20jcv9dk5s8b05pw8sj-libidn-1.43.nix).out} ${(import ../store/2wyknbzgp72s7mdh8x8yi6xnhhl6jijr-curl-8.6.0.nix).out} ${(import ../store/fgkqjrdn617xa5skjydv69a6m0m6vd43-nettle-3.10.1.nix).out} ${(import ../store/na7qqfh8f7xc0jhwmxcp56gz8wa3anna-libidn2-2.3.7.nix).out} ${(import ../store/4l0i33ky2hfy4zzqdmixhcpcrl9kkilc-mit-krb5-1.21.nix).out} ${(import ../store/zsil4zzf1iiwcbm5n9kzl6mr0k6a22c2-libtasn1-4.20.0.nix).out} ${(import ../store/yil0hfv0h2mrwh11rz48m9033p301lj2-p11-kit-0.24.1.nix).out} ${(import ../store/cpgq8y8gyg0bjhyk4m6k22gkncp4cgzg-libpsl-0.21.5.nix).out} ${(import ../store/210y6xm5w7kw1w8d6vx51l5yw50wsmdw-nghttp2-1.58.0.nix).lib} ${(import ../store/hsfkwglj2qzj7mlibrr34ga0rwspf53p-zlib-1.3.1.nix).out}";
}
