# Generated by guix-transfer
builtins.derivation {
  name = "mkdir";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-PGgCATDW2BOPdvEjHVF0VVus/dr82fWz9lbXeV1dfow=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  url = "https://ftpmirror.gnu.org/guix/bootstrap/i686-linux/mkdir?id=44f07d1dc6806e97c4e9ee3e6be883cc59dc666e";
  executable = "1";
}
