# Generated by guix-transfer
builtins.derivation {
  name = "compiler-rt-13.0.1.src.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''compiler-rt-13.0.1.src.tar.zst-builder''; path = ./../sources/sazjrl4k8r8w5qdnaqym02hi73yyq9by-compiler-rt-13.0.1.src.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "compiler-rt-13.0.1.src.tar.zst-builder"; path = ./../sources/sazjrl4k8r8w5qdnaqym02hi73yyq9by-compiler-rt-13.0.1.src.tar.zst-builder; })
    (builtins.path { name = "clang-13-remove-crypt-interceptors.patch"; path = ./../sources/k5qy21qb24wcqfrf498snc3pwgjj0h1d-clang-13-remove-crypt-interceptors.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "clang-runtime-13-glibc-2.36-compat.patch"; path = ./../sources/7yvx3dri9izsnjwfrac3l1bhpdk33c1p-clang-runtime-13-glibc-2.36-compat.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/v9sn5mw54rwax3b96iz4gajq79phw9q1-compiler-rt-13.0.1.src.tar.xz.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
