# Generated by guix-transfer
builtins.derivation {
  name = "tar";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-umIb/2rcLp44H1kH4Ohq0isZFnhATh8oiKWpJPoCAx0=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  url = "https://ftpmirror.gnu.org/guix/bootstrap/i686-linux/tar?id=44f07d1dc6806e97c4e9ee3e6be883cc59dc666e";
  executable = "1";
}
