# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/tmux/tmux"; rev = "refs/tags/3.6a"; hash = "sha256-VwOyR9YYhA/uyVRJbspNrKkJWJGYFFktwPnnwnIJ97s="; name = "tmux-3.6a-checkout"; fetchSubmodules = false; }
