# Generated by guix-transfer
builtins.derivation {
  name = "inetutils-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''inetutils-runtime-env-builder''; path = ./../sources/7rq00rjxhk41wq1rqdwjllpw2j19vqyb-inetutils-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "inetutils-runtime-env-builder"; path = ./../sources/7rq00rjxhk41wq1rqdwjllpw2j19vqyb-inetutils-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/pssx3gb12srq4abpjxxcsmb05lpm28wg-inetutils-2.5.nix).out} ${(import ../store/ls8wpvkps6yn0w1lgwhz6vrhlgp288cv-ncurses-6.2.20210619.nix).out} ${(import ../store/x8wnhf1f9dq7daq30dasl09m26mj4cm1-libxcrypt-4.4.38.nix).out} ${(import ../store/hzi7w1lfvwcbm1xfw6dvris7pgsksvi3-shadow-4.13.nix).out} ${(import ../store/l7s9zzf7a1i1kzdb2h4zcc2q27lvmx11-readline-8.2.13.nix).out} ${(import ../store/1r7ml8wichijf5wf0d0j8yksp7sagsfz-coreutils-9.1.nix).out}";
}
