# Generated by guix-transfer
builtins.derivation {
  name = "shepherd-1.0.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5IjFhchBjfbo9HbcqBtykQ8zfJzTYI+0Z95SYABAANY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/shepherd-1.0.9.tar.gz/sha256/1mh080060lnycys8yq6kkiy363wif8dsip3nyklgd3a1r22wb274";
}
