# Generated by guix-transfer
builtins.derivation {
  name = "ghostscript-9.56.1.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ghostscript-9.56.1.tar.zst-builder''; path = ./../sources/p6919l866av26xpa0ldvxjdayi8x0kf0-ghostscript-9.56.1.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ghostscript-no-header-uuid.patch"; path = ./../sources/9r0708vaxixcgf47rp5dgl8dix40hvay-ghostscript-no-header-uuid.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "ghostscript-9.56.1.tar.zst-builder"; path = ./../sources/p6919l866av26xpa0ldvxjdayi8x0kf0-ghostscript-9.56.1.tar.zst-builder; })
    (builtins.path { name = "ghostscript-CVE-2023-36664-fixup.patch"; path = ./../sources/afcv5nnlk5idc7hvjanbs28kzi98maan-ghostscript-CVE-2023-36664-fixup.patch; })
    (builtins.path { name = "ghostscript-no-header-creationdate.patch"; path = ./../sources/0hcyazmvxbifxfw1pzld0bvl2kj6crmd-ghostscript-no-header-creationdate.patch; })
    (builtins.path { name = "ghostscript-no-header-id.patch"; path = ./../sources/gw94g4x32ikccpazz0vlf98yq31m562b-ghostscript-no-header-id.patch; })
    (builtins.path { name = "ghostscript-CVE-2023-36664.patch"; path = ./../sources/kdmj0fbs2hdslbiv2x2lgznsgm08xry9-ghostscript-CVE-2023-36664.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 5))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/13g5nkhlg2b6cd0lqnsawsybhjzk9d52-ghostscript-9.56.1.tar.xz.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out}";
}
