# Generated by guix-transfer
builtins.derivation {
  name = "binutils-2.44.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/ilx7jgmpnczwgg03f8bmcg07b3k69ka1-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-2.44.tar.zst-builder''; path = ./../sources/hiriln909h4m8ivq0qd8x246rk8g6r32-binutils-2.44.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "binutils-2.44.tar.zst-builder"; path = ./../sources/hiriln909h4m8ivq0qd8x246rk8g6r32-binutils-2.44.tar.zst-builder; })
    (builtins.path { name = "binutils-loongson-workaround.patch"; path = ./../sources/zhx3zch54xs01i4pi5675xfkd4fix9b7-binutils-loongson-workaround.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "binutils-2.41-fix-cross.patch"; path = ./../sources/4432hk9wr0a70vgnxsj8jlfp9k6mnmig-binutils-2.41-fix-cross.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/cl85nwjbwhj8dcbjlzx1fh8g4ylj326w-xz-5.4.5.nix).out} ${(import ../store/v0bxp92fzi4vbicznydihk67syh15m2s-tar-1.35.nix).out} ${(import ../store/p7mrzpwg0998qbyvs2d09064imm80pjn-bzip2-1.0.8.nix).out} ${(import ../store/9kiw1fivijh536ldqyq6bb7d4jyl1pla-patch-2.7.6.nix).out} ${(import ../store/ra3wzsypbcdzxla02vijbx62mqcydqn6-zstd-1.5.6.nix).out} ${(import ../store/3ay2f76mz77n73xsxcq716326sxyvx5x-binutils-2.44.tar.bz2.nix).out}";
}
