# Generated by guix-transfer
builtins.derivation {
  name = "kbd-2.5.1.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-zN9FI4emOAlz0pJzY+nLuTn6IGiRWm+Tf/nSRSICRoM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/kbd-2.5.1.tar.xz/sha256/10s608i4blprgy9nynlid0hglfdrrgln6wwjs9rhjf56hwilbpyc";
}
