# Generated by guix-transfer
builtins.derivation {
  name = "grep-3.11.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/s9sqygnwvd22c4lchcpm0sd17rkardsz-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/jxhj6dpv7z15z04aikx234pskvw4q06l-module-import-compiled.nix).out}"
    "${builtins.path { name = ''grep-3.11.tar.xz-builder''; path = ./../sources/k7fkdpixsgzac39zkjmr8ajx6hx1wiyb-grep-3.11.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "grep-timing-sensitive-test.patch"; path = ./../sources/98i61ysx8vaqlldmacy12hizs0y83f6y-grep-timing-sensitive-test.patch; })
    (builtins.path { name = "grep-3.11.tar.xz-builder"; path = ./../sources/k7fkdpixsgzac39zkjmr8ajx6hx1wiyb-grep-3.11.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/3nf4n4p62kscys0lssy35r88l0vpgvrz-grep-3.11.tar.xz.nix).out} ${(import ../store/9g4hwdddd5p298wj8a2w1lqkz68w6w4c-bootstrap-binaries-0.nix).out}";
}
