# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/acmel/dwarves"; rev = "refs/tags/v1.29"; hash = "sha256-ke7WIIz0ZURw3Pgmt7WNL9WPbcv5B998Rflw/8/JQ8U="; name = "dwarves-1.29-checkout"; fetchSubmodules = false; }
