# Generated by guix-transfer
builtins.derivation {
  name = "guile-png-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/3lr2p38r3381kml7ilaj08v3z6ggv5hg-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/yrhlh925n8qfjp7k2dlyq5gndxnw8n81-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-png-runtime-env-builder''; path = ./../sources/vrq5brfy8r3kmmsim6dch4wq5slam7aw-guile-png-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    (builtins.path { name = "guile-png-runtime-env-builder"; path = ./../sources/vrq5brfy8r3kmmsim6dch4wq5slam7aw-guile-png-runtime-env-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/hcs3bfr9blgcnj8mmmpvq8r26brd8pgg-guile-zlib-0.2.2.nix).out} ${(import ../store/ii6bvyr5lzrr8j3rlka56gmxfp1yyr9r-libgc-8.2.8.nix).out} ${(import ../store/d8cphs5rpasas9d5a00c5p8ln13i6y8l-guile-png-0.8.0.nix).out} ${(import ../store/kv6l4iscw8apd96k6x1mpr3wk1ax2057-guile-3.0.9.nix).out} ${(import ../store/n34vvis15qy96fvl88dcd8y400wf8pwd-guile-lib-0.2.8.1.nix).out} ${(import ../store/al585zfr2ydg7jn7dzzy2mjhndfmy7v2-bash-minimal-5.2.37.nix).out} ${(import ../store/5hbj22aib05nhxkhv122hxwnjkiqm2sm-guile-smc-0.6.4.nix).out} ${(import ../store/8wa5z6p00wr4dgwx8rplfdjq8vkjdmqk-libunistring-1.3.nix).out}";
}
